### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Salamandar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by kay0u** [comment]
Some feedback after upgrading to testing branch:

nginx doesn't use the port configured `/etc/yunohost/apps/sonarr/settings.yml` (8989 in this file, 8100 in nginx) nor the baseurl field in `/var/lib/sonarr/config.xml`.

After fixing this, my catalog is empty (not migrated from my previous install

**Comment by tituspijean** [comment]
@kay0u I cannot replicate any of your issues 😅 

- No port issues upon upgrading
- No database issue upon upgrading
- Self-update indeed does not work: package download, self-backup work, but when Sonarr self-restarts it is still at the previous version. Removing `@privileged` does not fix the issue.

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
If someone can find how to fix the following error due to a damn missing/required new line at the end of the config file...

> Error: Apparently the log is telling that 'some file got manually modified' ... which should not happen, considering that no human modified the file ... ! This is usually symptomatic of something that modified a conf file after installing it with ynh_add_config. Maybe usigin ynh_store_file_checksum can help, or maybe the issue is more subtle!

**Comment by tituspijean** [comment]
!testme

**Pull request merged**
