### PR TITLE
Make sure the internal auth system is disabled

### PR DESCRIPTION
**Pull request by tituspijean**
## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by Salamandar** [comment]
I don't really understand how this change triggers so much log/warning/systemd start issue…

**Comment by Salamandar** [comment]
> Application started

is not is the systemd start log anymore :|

**Comment by tituspijean** [comment]
> > Application started
> 
> is not is the systemd start log anymore :|

erf I changed the logging level from info to warn. My bad.

**Comment by tituspijean** [comment]
!testme

**Pull request merged**
